//
//  Reading.swift
//  SVSH3.0
//
//  Created by Shachar on 10/25/22.
//

import Foundation
struct Reading {
    
    var title : String
    var text : String
}

extension Reading {
    static let sampleReadings: [Reading] =
    [
        Reading(title: "What is Sexual assult", text:  "The term sexual assault refers to sexual contact or behavior that occurs without explicit consent of the victim. Some forms of sexual assault include: \n Attempted rape \nFondling or unwanted sexual touching \n Forcing a victim to perform sexual acts, such as oral sex or penetrating the perpetrator’s body \n Penetration of the victim’s body, also known as rape \n he majority of perpetrators are someone known to the victim. Approximately eight out of 10 sexual assaults are committed by someone known to the victim, such as in the case of intimate partner sexual violence or acquaintance rape. The term “date rape” is sometimes used to refer to acquaintance rape. Perpetrators of acquaintance rape might be a date, but they could also be a classmate, a neighbor, a friend’s significant other, or any number of different roles. It’s important to remember that dating, instances of past intimacy, or other acts like kissing do not give someone consent for increased or continued sexual contact. In other instances the victim may not know the perpetrator at all. This type of sexual violence is sometimes referred to as stranger rape. Stranger rape can occur in several different ways "),
        
        Reading(title: "SUSC :)", text: "Section 1: Establishment \n1.1    This bylaw shall apply to all stipends disbursed to ASUC officials, including executive officers, senators, programs, commissions, and their staffs. This bylaw shall not apply to sponsored student organizations. This bylaw shall not apply to the Administrative Office (ASUCBL 1103). \n 1.1.1    Registered student organizations shall not be eligible to receive ASUC funding for the purpose of receiving stipends. \n1.2    Stipends for all officials except for Executive Officers and Appointed Officers shall be disbursed on a semesterly basis. Unless otherwise noted in the bylaws or the General Budget, one half of the stipend shall be disbursed following the end of the fall semester and the remaining half shall be disbursed following the end of the spring semester. \n1.3    Stipends for Executive Officers and Appointed Officers shall be disbursed in three periods: twenty percent following the summer inter-semester period, forty percent following the fall semester, and forty percent following the spring semester. Executive Officers and Appointed Officers are expected to carry out ASUC functions over the summer inter-semester period."),
        
        Reading(title: "SUSC :(", text: "1.1    As this Title is intended to prevent financial irresponsibility, which could jeopardize the mission of the ASUC, this Title shall not be waived or suspended by the Senate. 2.1    A.S.U.C. Spending Restrictions Pursuant to Section 8, Article VI of the ASUC Constitution, all financial restrictions enumerated in this section may be waived or modified by the Finance Committee for specific operational units or groups; however, the Senate retains final authority.  No waiver shall be granted more than five regular ASUC Senate meetings after the event and/or purchase date except in the case of reimbursement as provided in Title III, Article 2.1(3), 2.1(4), and 2.1(5); or by two-thirds vote of the Senate. No ASUC funds may be used to: 1.    Purchase food and beverages; with no exceptions or waivers whatsoever for individual, single-use water bottles; 2.    Pay registration fees for Intramural teams; 3.    Purchase or reimburse a group for flyers (advertising) that do not display the words “Sponsored by the ASUC” or ; 4.    Purchase or reimburse a group for flyers (advertising) that do not indicate the degree of wheelchair accessibility to the event described by the flyer; 5.    Purchase or reimburse a group for stationery that does not display the logo of the ASUC; or 6.    Travel outside the Bay Area, (Bay Area consists of nine counties); 1) Alameda, 2) Contra Costa, 3) Marin, 4) Napa, 5) San Francisco, 6) San Mateo, 7) Santa Clara, 8) Solano, and 9) Sonoma; 7.    Pay for any costs related to local events that fall outside the geographic boundaries of Ashby, to the south, MLK to the west, Cedar to the north, and the hills of the east 8.     Pay for any prizes and gifts for individuals. 9.    Purchase alcoholic beverages or illegal substances; or 10.    Fund off-campus political activities - such as local, state, or national political campaigns, candidates, or ballot initiatives. a.     This shall not preclude the ASUC from providing monies for educational initiatives or to publicize positions taken by the Senate. Neither educational initiatives nor publicized positions may ask the public to adopt a specific position. 11.    Fund any activity or group which discriminates in its method of recruitment and acceptance for membership as per Article VI, Section 7, Subsection C of the ASUC Constitution or on the basis of gender identity, immigration status, mental ability or socioeconomic status. 12.     Insurance premiums for hazard 2 and 3 level events on campus 13.     Non-essential latex products such as balloons and rubber bands. Contraceptives or personal protective equipment shall not be included in this definition. 14.    Single-use styrofoam and polystyrene products. 15.     Glossy or plastic-finished flyers with no exemptions or waivers whatsoever. 16.     Funds shall not be used for RSO member stipends, pursuant to ASUCBL 2151.")
    ]
}
